### ISSUE TITLE
Character "q" slant displayed incorrectly

### ISSUE THREAD

**Issue by thecodingwizard** [rsms/inter#360]
**Describe the bug**

The lowercase character q is slanted in the wrong direction when italicized:
![image](https://user-images.githubusercontent.com/7865976/112788028-cb51a700-900e-11eb-81b4-98550454e2dc.png)

**To Reproduce**
1. https://rsms.me/inter/#variable
2. Max out "slant"
3. The character `q` is slanted in the wrong direction

**Expected behavior**
The character `q` should be slanted in the right direction

**Screenshots**
(see above)

**Environment**
- OS: Windows 10
- App that renders the font: Chrome 89
- Version of font: Oops not sure, I think `Inter var`? Whatever `https://rsms.me/inter/inter.css` corresponds to

**Additional context**
I only noticed this issue recently; I think it was fine before.

**Comment by thecodingwizard** [comment]
this appears to have been fixed now; thanks!

**Comment by rsms** [comment]
:–)

**Comment by rsms** [comment]
Reopening this issue since there's a bug in Glyphs 3 that keeps reverting the change so the italic "q" is now again broken. Will fix it manually instead of using transforms in Glyphs at the cost of a slight font size increase and future manual labor :•)

**Comment by rsms** [comment]
[Released with v3.18](https://github.com/rsms/inter/releases/tag/v3.18)

**Comment by manuelmeister** [comment]
This problem still persists in the Display version. I just built it locally.

**Comment by bennetfabian** [comment]
> This problem still persists in the Display version. I just built it locally.

I'm also experiencing it when building Inter Display locally. Could you also do the manual work you've done to Inter's normal version to the Display version? @rsms

**Comment by FryingggPannn** [comment]
I still see this problem in Inter Display, should I reopen this issue?
