### ISSUE TITLE
Italics don't work with variable webfont

### ISSUE THREAD

**Issue by ypomortsev** [rsms/inter#78]
**Describe the bug**
Text with "font-style: italic" using "Inter UI var" does not show as italic in RC3

**To Reproduce**
1. Download [inter-ui-var-italic-test.txt](https://github.com/rsms/inter/files/2430255/inter-ui-var-italic-test.txt), rename to .html and move into "Inter UI (web)"
2. View it

**Expected behavior**
Both lines are italic

**Screenshots**

Got:
![got](https://user-images.githubusercontent.com/857581/46240761-40ba5f00-c361-11e8-8c12-ff454a21c5c5.png)

Want:
![want](https://user-images.githubusercontent.com/857581/46240762-43b54f80-c361-11e8-9bff-f8e81da37955.png)

**Environment**
- OS: Windows 10
- Firefox 62.0.2, Chrome 69.0.3497.100
- Fonts: Inter UI Italic. 3.0;2eafdfa3

**Comment by rsms** [comment]
Fixed in https://github.com/rsms/inter/releases/tag/v3.0-rc4

**Comment by ypomortsev** [comment]
Thanks! I'm seeing two issues in RC4:

1. On Firefox, the variable italics are "too italic":

![inter-ui-3 0-rc4-italics](https://user-images.githubusercontent.com/857581/46330076-03a2d680-c5c6-11e8-9952-0a3dac0cb0fe.png)

2. On Chrome, the variable font still doesn't show italics :(

![inter-ui-3 0-rc4-italics-chrome](https://user-images.githubusercontent.com/857581/46330117-2339ff00-c5c6-11e8-846c-50759db4e105.png)

Tested with same browser versions and file as above, just using the RC4 unhinted woff2s.
